services:
  - type: web
    name: terminaltyper
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0 # Or whatever version you prefer
      - key: SECRET_KEY
        generateValue: true
